FROM quay.io/rbreslow/lua:%%LUA_VERSION%%

RUN \
    buildDeps="\
    alpine-sdk \
    lua$LUA_VERSION-dev \
    " && \
    apk add --no-cache $buildDeps && \
    luarocks install luacheck %%VERSION%% && \
    apk del $buildDeps curl unzip

ENTRYPOINT ["/usr/local/bin/luacheck"]
